DROP DATABASE IF EXISTS ATIVIDADE1;

CREATE DATABASE ATIVIDADE1;

USE ATIVIDADE1;

CREATE TABLE CADASTRO(
IDCADASTRO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45) NOT NULL, 
CELULAR INT NOT NULL,
COMERCIAL INT,
RECADO INT,
PRIMARY KEY(IDCADASTRO)
);
