DROP DATABASE IF EXISTS EXERCICIO02_CANTINA;

CREATE DATABASE EXERCICIO02_CANTINA;

USE EXERCICIO02_CANTINA;

CREATE TABLE PEDIDO(
IDPEDIDO INT NOT NULL,
CLIENTE_NOME VARCHAR(45) NOT NULL,
PEDIDO_DATA DATE NOT NULL,
PEDIDO_HORA TIME NOT NULL,
PRIMARY KEY(IDPEDIDO));

CREATE TABLE PRODUTO(
IDPRODUTO INT NOT NULL,
PRODUTO_PRECO VARCHAR(15) NOT NULL,
PRODUTO_NOME VARCHAR(45) NOT NULL,
PRIMARY KEY (IDPRODUTO));

CREATE TABLE SOLICITAR(
IDPEDIDO INT NOT NULL,
IDPRODUTO INT NOT NULL,
PRIMARY KEY(IDPEDIDO, IDPRODUTO),
FOREIGN KEY(IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO),
FOREIGN KEY(IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO));



