DROP DATABASE IF EXISTS EXERCICIO01;

CREATE DATABASE EXERCICIO01;

USE EXERCICIO01;

CREATE TABLE VEICULO(
ID_VEICULO INT NOT NULL,
ANO_FABRICACAO DATE NOT NULL,
MODELO VARCHAR(50) NOT NULL,
MARCA VARCHAR(50) NOT NULL,
PLACA_VEICULO VARCHAR(15) NOT NULL,
ID_RENAVAM INT NOT NULL,
UF_REGISTRO CHAR(2) NOT NULL,
DATA_REGISTRO DATE NOT NULL,
DOCUMENTO_EMITIDO VARCHAR(100) NOT NULL,
PRIMARY KEY(ID_VEICULO, ID_RENAVAM)
); 