DROP DATABASE IF EXISTS DBATIVIDADE5;
CREATE DATABASE DBATIVIDADE5;
USE DBATIVIDADE5;
CREATE TABLE ESTACIONAMENTO (
ID_ESTACIONAMENTO INT NOT NULL AUTO_INCREMENT
,MARCA VARCHAR(45) NOT NULL
,MODELO VARCHAR(45) NOT NULL
,ANO_FABRICACAO INT
,ANO_MODELO INT
,PLACA VARCHAR(45)
,COR VARCHAR(45)
,NUM_CHASSI VARCHAR(45)
, PRIMARY KEY (ID_ESTACIONAMENTO)
);

